const articlesData = [
    {
        id: 1,
        author: 'Mike Zamora',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 2,
        author: 'Sonia Lane',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 3,
        author: 'Elaine Pearce',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 4,
        author: 'Isha Nguyen',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 5,
        author: 'Robyn Rush',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 6,
        author: 'Paul Wu',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 7,
        author: 'Harris Chaney',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 8,
        author: 'Aamina Johnston',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 9,
        author: 'Franciszek Foley',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 10,
        author: 'Sophie Lozano',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 11,
        author: 'Huw Todd',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 12,
        author: "Nevaeh O'Doherty",
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 13,
        author: 'Cole Mcdonald',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 14,
        author: 'Faith Doyle',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 15,
        author: 'Hussain Mendez',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 16,
        author: 'Seamus Patel',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 17,
        author: 'Stanley Vang',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 18,
        author: 'Daniella Higgins',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 19,
        author: 'Bilal Hanna',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
    {
        id: 20,
        author: 'Khadija Chambers',
        article: {
            arti: "Loremipsum",
            arti2: "Loremipsum",
            arti3: "Loremipsum",
            arti4: "Loremipsum",
            arti5: "Loremipsum",
            arti6: "Loremipsum",
            arti7: "Loremipsum",
            arti8: "Loremipsum",
            arti9: "Loremipsum",
            arti10: "Loremipsum",
            arti11: "Loremipsum",
            arti12: "Loremipsum",
            arti13: "Loremipsum",
            arti14: "Loremipsum",
            arti15: "Loremipsum",
            arti16: "Loremipsum",
            arti17: "Loremipsum",
            arti18: "Loremipsum",
            arti19: "Loremipsum",
            arti20: "Loremipsum",
        }
    },
];
export default articlesData;